language: scala
scala:
  - 2.11.8
jdk:
  - oraclejdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION client/fastOptJS test

sudo: required

services:
  - docker

deploy:
  provider: script
  script:
#    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - sbt docker:publish

  on:
    branch: master

cache:
  directories:
  - $HOME/.sbt/0.13
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/cache
  - $HOME/.sbt/launchers
  - $HOME/.ivy2
  - $HOME/.coursier

before_cache:
  - du -h -d 1 $HOME/.ivy2/
  - du -h -d 2 $HOME/.sbt/
  - du -h -d 4 $HOME/.coursier/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.coursier/cache -name "*.lock" -type f -delete
