language: scala
scala:
- 2.11.8
jdk:
- oraclejdk8

sudo: required
services:
- docker

before_script:
- sbt ++$TRAVIS_SCALA_VERSION compile

script:
- sbt ++$TRAVIS_SCALA_VERSION test

before_deploy:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

deploy:
  provider: script
  skip_cleanup: true
  script:
  - sbt docker:publish
  on:
    branch: master




cache:
  directories:
  - "$HOME/.sbt/0.13"
  - "$HOME/.sbt/boot/scala*"
  - "$HOME/.sbt/cache"
  - "$HOME/.sbt/launchers"
  - "$HOME/.ivy2"
  - "$HOME/.coursier"
before_cache:
- du -h -d 1 $HOME/.ivy2/
- du -h -d 2 $HOME/.sbt/
- du -h -d 4 $HOME/.coursier/
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
- find $HOME/.coursier/cache -name "*.lock" -type f -delete
env:
  global:
  - secure: Krcrfk0kiqEJ2JNSgT4Mz/d2e8QRTk73QICgMzJqkFu9e57e/RzWC0XgPJBclrbjwDMZhg1KLq2v0yOD8FwS5UYrWxPNie8V7NFqkWoM2lKwXHFZ9BUuzzZI1jwPJ2clHCSaEQzh9jC6WmaFSQsjb8mRmva/DrwMFZq5toLcEVwLm4L22X3wAk4cBKSKQETX56urqsjI7w5XgjV09tHmu4NHgTEQM+IUiAYNA35fD4cb4cNy2/ezw9JHFSME5PPTXI8u/EgItmdswP9HavK5Qzgm6ARetnn3oUBlJ3MZyd7nzbKEdKZeRU6/2Kn5ygvd4xQS8APPA7UuC/Tn7ULeHpj494ugwxdKzaT7UTcFo9d+gaA1pip3d9xKxBrGC/8B8SkRpPJRbXRzinjytgwiDD8mv39549oowRxQ/x7dpEfEALOSBlSsCG8M7G1rOjQz87ZTYVCX9qtbK37Uai7pv8sOOznhvmafbmTj4/nqGvY/PaVdMB1G88DL4KdHb2ZjTioPfcvmKfHQ888teDRySdeTAW+gvLb0p3khB3N1kekUfgwYpPK8/W+aTmqo+cnHpaTmeeAKDI+NpVzU/K+yjzXsE3M0cxMnr56KgkzMlloDh3q6Ga8vd7tC6Tg8PDSKBU6IY9b80umPSO+8QSg/AMeBeKJmaAd+rSRFMztnY78=
  - secure: nUPtlM2PHBvCINKs88QCTUjsMD+9/98vvtqsbKtWh9JUK9bSt3vhVqcli6ABTprFc8MknXAJuaReCITlJeqjdui/yEFSrrHFBgFaSv8j9QUGNNHB9/vNhaiEV3WzPZWow4jDtYuXZOLIrmcz/U6TPFAkQOzgR6JQRvyGcxlfmRMUcI1YCK4lGM2BIY1kLttxSAH6w4JB6y4f3kga640oCMqmiIyNfmKXnmLnHt7x/4oO7RhHznclKlA+M5KDWkZq/IOW7WF+t5UgG6NZokWRKlbv0PaZ5iLeTJTXHaeYcnwkFTXbwUk9WGPaU7RvAul4cnqlTY9HZI4gABrmE1yctiPZfhC17zzki4WyYbhL4kUciavvcE4PAqLRDTr12LZ2PrbJncZBtZccq3M4bAvr8+EtT4xvTXSOqtua12hDye/8qsUk9hzpuL7tbPXYbMfV+vvou9sjw+u0W97soqRxqXlz74YHuSibxvOxcDV1jnAEVippm84BNZu+WWfEoyNhExg7HNrsDvTS5tRRDSqzofX3lCDD1/nR3osb0VN/Vf8XJC8zEb2BRbTuS0Rpork0luhZf0huqjd13UjJWVEgZVp4XjLV5c0zzwRTbW0fWJgNM+zksohDJ7Otgu9SOWbqMoobBp5onYJ2PejyeHLvowEIniWNeTuiPP/3Iwgm/Qk=
  - secure: DH/yOTPh7ijmpM6HZVfcyjDUckcnqRUCUgAP7tD6A2zyyOxobgOm8+kxvu3YoII9s96+ZC76yWKB4D8lJDhJAjm5Cu8+MtacPGIGM6ltm6qPn5BkhdoBq3RNv2eSOcr2LhSzKG5WK2dOuYtPXJznH0LuHrPQAnFO7htENt7THM30dUaBRqUNeQGJAeWoFobTo9hifeABMDgH2HaC74VRjCbxFfDbnbFZbNpoItNljMCjzYK6Qx1OkZ4qpnV7yfxO0Y8gURq2dwP64zqjxBI1ORETBHEdQyELzX9dRPZO7bUG/5/8KCC/LsOKR2IA8dJmJ7f1D7ERwTTQnDzkEh6+wlyW/6j3f9aLb59KNL5si67jducfWGZnn8d7F0RMVd4wcx8KmKKS9xiK/5LZhYkDNFUo4KD7ubXY77UxY75qEk6XweChvR9IKQjjJXOgBJcEvM7xTpYhJnO1DAj3A2o5IlVf/HOXUeMhsAO5VOt8w5lWzX3VgJ+doGodrdAkqBcRw5dQbY19ORdfoSzMtdEc5UtbRgNFv/qGv0CpJa3Htz5xq5DiOwU67DY1PahEz2fTEUyvOff4E46pTu36ib26yI7q+OTXr9e1sP6o/89yIxnXeOZhVt+YEkyfargi8LtJAqJqgT1ZepWQNTqzN4pEdK3KUGLjJmg/6a6tfYvW6/k=
