---

- hosts: gregd.me
  user: grogs
  sudo: True

  vars:
    app_name: cineworld-backend
    webapps_dir: /srv/webapps
    #wsgi_file: wsgi.py

  tasks:
    - name: deploy JAR
      action: copy src={{archivePath}} dest=${webapps_dir}/{{archiveName}}
      notify:
        - restart app

    - name: create supervisor program config
      action: template src=templates/supervisor.ini dest=/etc/supervisor/${app_name}.ini
      notify:
        - restart app

    #- name: create nginx site config
    #  action: template src=templates/nginx_site.conf dest=/etc/nginx/sites-available/${app_name}.conf
    #  notify:
    #    - restart nginx

   # - name: link nginx config
    #  action: file src=/etc/nginx/sites-available/${app_name}.conf dest=/etc/nginx/sites-enabled/${app_name}.conf state=link

   # - name: start app
   #   action: supervisorctl name=${app_name} state=started

  handlers:
    - name: restart app
      action: supervisorctl name=${app_name} state=restarted

    #- name: restart nginx
     # action: service name=nginx state=restarted
